#!/usr/bin/with-contenv bash

echo "**** Install mesa amd packages ****"
apt-get install -y \
	vainfo \
	mesa-va-drivers \
	mesa-vdpau-drivers \
	libdrm-amdgpu1 \
	libavutil56 \
	rocm-opencl-runtime
apt-get clean
